######################################################################################################
#
# Here you can configure the rules for the proxy.
# This example is configuration of sharding rule.
#
# If you want to use sharding, please refer to this file;
# if you want to use master-slave, please refer to the config-proxy-rangerouting-masterslave.yaml.
#
######################################################################################################

schemaName: sharding_db

dataSourceCommon:
  username: root
  password:
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 200
  minPoolSize: 200
  maintenanceIntervalMilliseconds: 30000

dataSources:
  press_test_0:
    url: jdbc:mysql://ss.benchmark.rangerouting.sharding.ds0:3306/baitiao_test?serverTimezone=UTC&useSSL=false
  press_test_1:
    url: jdbc:mysql://ss.benchmark.rangerouting.sharding.ds1:3306/baitiao_test?serverTimezone=UTC&useSSL=false
  press_test_2:
    url: jdbc:mysql://ss.benchmark.rangerouting.sharding.ds2:3306/baitiao_test?serverTimezone=UTC&useSSL=false

rules:
  - !SHARDING
    tables:
      sbtest:
        actualDataNodes: press_test_${0..3}.sbtest${0..99}
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithm:
              type: INLINE
              props:
                algorithm.expression: press_test_${id % 3}
        tableStrategy:
          standard:
            shardingColumn: k
            shardingAlgorithm:
              type: INLINE
              props:
                algorithm.expression: sbtest${k % 100}
        keyGenerator:
          type: SNOWFLAKE
          column: id
    bindingTables:
      - sbtest