dataSources:
  shardingsphere_benchmark: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.fullrouting.encrypt.ds0:3306/shardingsphere_benchmark?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true

rules:
  - !ENCRYPT
    encryptors:
      encryptor_aes:
        props:
          aes-key-value: '123456abc'
        type: AES
    tables:
      sbtest:
        columns:
          c:
            cipherColumn: c
            encryptorName: encryptor_aes

props:
  max.connections.size.per.query: 10
  acceptor.size: 200  # The default value is available processors count * 2.
  executor.size: 200  # Infinite by default.
  query.with.cipher.column: true
  sql.show: false
  allow.range.query.with.inline.sharding: false
  check.table.metadata.enabled: false