dataSources:
  baitiao_test: !!com.zaxxer.hikari.HikariDataSource
    username: root
    password:
    jdbcUrl: jdbc:mysql://ss.benchmark.fullRouting.encrypt.ds0:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true

shardingRule:
  encryptRule:
    tables:
      sbtest99:
        columns:
          c:
            cipherColumn: c
            encryptor: encryptor_aes
    encryptors:
      encryptor_aes:
        type: aes
        props:
          aes.key.value: 123456abc
