
dataSources:
  ds_master: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://ss.benchmark.fullrouting.masterslave.master.ds0:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true
  ds_slave0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://ss.benchmark.fullrouting.masterslave.slave.ds0:3306/baitiao_test?serverTimezone=UTC&useSSL=false
    username: root
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maximumPoolSize: 200
    password:
    dataSourceProperties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      netTimeoutForStreamingResults: 0
      useServerPrepStmts: true

shardingRule:
  masterSlaveRules:
    ms_ds_0:
      masterDataSourceName: ds_master
      slaveDataSourceNames:
        - ds_slave0
      loadBalanceAlgorithmType: ROUND_ROBIN
